### ISSUE TITLE
Include fakeroot option

### ISSUE THREAD

**Issue by ruanformigoni** [FS-make-simple/fusecompress#1]
Hello there,

I currently use this project with fuse2fs and proot. In summary, I do a `chroot` in another gnu system that is mounted in a `fusecompress` volume, for transparent compression, however, it fails on some tasks due to a missing `fakeroot` option as it is available in fuse2fs, implementation [here](https://github.com/tytso/e2fsprogs/blob/master/misc/fuse2fs.c). I'm trying to implementing this, would it be something desirable for the main project?

Thanks,

**Comment by zvezdochiot** [comment]
@ruanformigoni say:
>however, it fails on some tasks due to a missing fakeroot option

He shouldn't work like that. And it does not meet such tasks in terms of productivity and efficiency. For your purposes, only a combination of `squashfs` and a spanning filesystem will be effective. Even if you implement the `fakeroot` feature, it will not be required. But you can try.

**Comment by ruanformigoni** [comment]
Thanks for the feedback. Would you know how to get the value of `fuse_get_context()->private_data`? It appears to be NULL in the current implementation. One thing I'm trying is to replace `lchown` with `fuse_fs_chown`.

**Comment by zvezdochiot** [comment]
@ruanformigoni say:
>It appears to be NULL in the current implementation.

Exactly. Therefore, it is not clear to me how you are going to use `fusecompress` in the way you indicated.

**Comment by ruanformigoni** [comment]
It did it! :smile:  It was NULL because of the custom init function, I re-implemented it to create the `private_data` as a return value. After that you need to pass the `nosuid` and the `nodev` params to fuse. 

```cpp
  fusev[fc.fusec++] = "-onodev";
  fusev[fc.fusec++] = "-onosuid";
```

And now `chown root:root ./my-file` works inside the filesystem without superuser privileges.
